CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS ulw_auth;
CREATE SCHEMA IF NOT EXISTS ulw_pm;
CREATE SCHEMA IF NOT EXISTS ulw_ad;
CREATE SCHEMA IF NOT EXISTS ulw_cg;
CREATE SCHEMA IF NOT EXISTS ulw_cr;
CREATE SCHEMA IF NOT EXISTS ulw_ta;
CREATE SCHEMA IF NOT EXISTS ulw_dp;
CREATE SCHEMA IF NOT EXISTS ulw_core;
